### ISSUE TITLE
名前

### ISSUE THREAD

**Issue by yantene** [yantene/hinano#30]
## お茶の間のイメージで〇〇の間

- renoma: 茶の間を再定義の re
- lenoma: リビングの l
- menoma: me
- zenoma: 究極の z
- fanoma: family の fa
- yanoma: yet another chanoma
- noma: いっそ

## 家のイメージ

- hinano: 奥の細道より
- nldk: n LDK
- subako: 巣箱。箱のイメージもある。
- wagaya: やっぱ我が家が一番落ち着くね。
- tagaya: 誰が家？

## 訪問のイメージ

- ojama: お邪魔します。
- knock: ノック。

**Comment by cflatech** [comment]
uchiwaに戻せば？
